### ISSUE TITLE
Error when Setup credentials

### ISSUE THREAD

**Issue by tproenca** [KnisterPeter/vscode-jira#11]
After inputing my credentials, I'm getting the following error:
```
request to https://jira-hzn.eng.vmware.com/rest/api/2/serverInfo failed,
reason: unable to verify the first certificate
```

**Comment by KnisterPeter** [comment]
Do you have a valid ssl certificate? The extension expects a proper ssl setup.
Maybe your certificate is self signed?

**Comment by tproenca** [comment]
Yes, the certificate is valid and signed by DigiCert.
Any other thoughts that could be causing that?

**Comment by KnisterPeter** [comment]
Can you execute the request `https://jira-hzn.eng.vmware.com/rest/api/2/serverInfo` in your browser?
The error about the certificate is probably from the requests the extension does.
Maybe DigiCert is not valid in electron (but I don't think so).

**Comment by tproenca** [comment]
Yes, it works fine.

I also, wrote a script to test if Electron would open the above URL, and the answer is also yes, it can open just fine.

**Comment by KnisterPeter** [comment]
I'll investigate further. Thanks for you help so far.
