### ISSUE TITLE
Absolute URL error when using absolute URL

### ISSUE THREAD

**Issue by wgj** [KnisterPeter/vscode-jira#12]
Encountered error "only absolute urls are supported" when trying to set up credentials (command palette `JIRA: Setup credentials`) when using `"jira.baseUrl": "https://jira.example.school.edu"`

<img width="774" alt="screen shot 2017-10-11 at 2 29 53 pm" src="https://user-images.githubusercontent.com/463564/31467963-aee2648c-ae90-11e7-980d-4e3523d6ff37.png">

vscode-jira version 0.4.0
vscode version 1.17.1

**Comment by KnisterPeter** [comment]
Can you try to open `https://jira.example.school.edu/rest/api/2/serverInfo` in your browser?

**Comment by wgj** [comment]
Successfully connects and displays diagnostics JSON object.

**Comment by KnisterPeter** [comment]
I've added an output channel where success or failures are logged.
Please update to `0.5.0`, try to connect to jira and have a look at the output of the JIRA channel (You can open it with the `Toggle output` command).

**Comment by wgj** [comment]
Good news, bad news.

Bad news: can not reproduce issue.
Good news: Output channel shows `Connected to JIRA server at 'https://jira.mednet.ucla.edu'`
