### ISSUE TITLE
FR: Option to automatically activate jira ticket by current git branchname

### ISSUE THREAD

**Issue by st-schneider** [KnisterPeter/vscode-jira#15]
It would be really cool if there was a feature that automatically activates by the currently checked out git branch name.
I don't know how complex the jira ticket names are only focusing on prefix and number here.
so if there is a ticket XX-YYYY and you are currently on the branch XX-YYYY-SOMETHINGSOMETHING or maybe even SOMTHING-BLA-XX-YYYY-ABC it would be cool if the appropriate ticket would be activated.
It should be optional since I guess some people name their branches differently.

**Comment by KnisterPeter** [comment]
Its a nice idea but very opinionated. I would probably accept this but allow for configuring a regular expression on matching branch names and issue names.

**Comment by st-schneider** [comment]
Was just a basic idea, regular expression sounds fine to me.

**Comment by dmstern** [comment]
I would prefer the other way round: https://github.com/KnisterPeter/vscode-jira/issues/32
