### ISSUE TITLE
Bug: Location of JIRA Ticket info in bottom bar is changing

### ISSUE THREAD

**Issue by st-schneider** [KnisterPeter/vscode-jira#16]
It seems that the position of the JIRA ticket information in the bottom bar is not consistent in the way that it stays at the same position in line with and without a selection of a ticket.

Before Selection
![image](https://user-images.githubusercontent.com/30625381/32041451-5dfc439e-ba34-11e7-9c0d-330f3901e7d6.png)

After Selection
![image](https://user-images.githubusercontent.com/30625381/32041481-78d10808-ba34-11e7-911c-63c2997d4e16.png)

**Comment by KnisterPeter** [comment]
Right. Currently it is too high in priorization.
