### ISSUE TITLE
No JIRA client configured. Setup baseUrl, projectNames, username and password

### ISSUE THREAD

**Issue by saumilsdk** [KnisterPeter/vscode-jira#17]
I have added the baseUrl and projectNames as well still it doesn't work

**Comment by balexandre** [comment]
same here, but I found out the pwd was wrong...

try this:

in `.vscode/settings.json` write the baseurl and projectNames

```javascript
{
    "jira.baseUrl": "https://yourclientname.atlassian.net\/",
    "jira.projectNames": "Your project KEY name"
}
```

then, bring the command palette with <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>P</kbd> (if Windows) and choose **Reload Window**

and after reloaded, open the command palette once again and choose **Jira: setup credentials** and add your email and password, or username and password (they both work).

**Comment by KnisterPeter** [comment]
The extension needs better error management and reporting.
Thanks for reporting back.

**Comment by fr-yunho** [comment]
@balexandre you saved my time! thx!
