### ISSUE TITLE
There are no entries to pick from 

### ISSUE THREAD

**Issue by balexandre** [KnisterPeter/vscode-jira#18]
I've setup the `baseUrl`, `projectNames` as well my credentials (tries both with username and email as username), but when I ask for **browse my issues** I always get 

> There are no entries to pick from

And if I try to activate an issue manually, I also get

> There are no entries to pick from

What am I missing??

my `.vscode/settings.json`: 

```javascript
{
    "jira.baseUrl": "https://quantads.atlassian.net\/",
    "jira.projectNames": "DEV board"
}
```

what am I missing?

projects:

![](https://s6.postimg.org/5cs08jj5t/screenshot_94.png)

my issues:

[![](https://s6.postimg.org/p7e1uodsx/screenshot_95.png)](https://s6.postimg.org/p7e1uodsx/screenshot_95.png)

**Comment by KnisterPeter** [comment]
I'll have to look into that. I can give you the JQL which is executed by the extension to have a look into that.

**Comment by balexandre** [comment]
I tried a bit using `https://jira.atlassian.com/rest/api/2/search?jql=` url and found out something that should be in the description ...

projects should be the `projectKey` and not the name ... in my case `DEV` and not `DEV board`

the correct settings are:

```javascript
{
    "jira.baseUrl": "https:\/\/quantads.atlassian.net\/",
    "jira.projectNames": "DEV"
}
```
found out using the advance search:

[![](https://s6.postimg.org/cpkfacpb5/screenshot_511.png)](https://s6.postimg.org/cpkfacpb5/screenshot_511.png)

in the projects page, use the **Key** value and not name

![](https://s6.postimg.org/bna8ryje9/screenshot_512.png)

after the correct setup, now all works out-of-the-box

**Comment by KnisterPeter** [comment]
Cool. I'll update the documentation on that. Hope it helps.
