### ISSUE TITLE
Feature: Add current task id to scm message

### ISSUE THREAD

**Issue by marcomattes** [KnisterPeter/vscode-jira#19]
I would find it useful if the ID always appears in the scm commit message input field based on the current task.

Example: NPROJECT-123: ### Your Message ###

**Comment by KnisterPeter** [comment]
Nice idea, but I'm not sure if this is possible with vscode.

**Comment by dmstern** [comment]
You could use git templates. They are supported by VSCode: https://github.com/Microsoft/vscode/issues/7830

Suggestion:
* Add an option to enable git commit templates (maybe some users are already using them for something else)
* On enabling this option: set `git config commit.template .git/vscode-jira-commit-template.txt`
* On changing the jira task: write the template content into that file: `NPROJECT-123: `
