### ISSUE TITLE
Cannot connect to jira

### ISSUE THREAD

**Issue by pawelmilka** [KnisterPeter/vscode-jira#24]
After extension update to version 0.5.1 I cannot connect to Jira anymore.
Output log:
Failed to contact JIRA server using 'https://jira.mydomain.com/jira/'. Please check url and credentials
Headers is not defined

**Comment by KnisterPeter** [comment]
Oh, this looks like a regression. I'll fix that.

**Comment by KnisterPeter** [comment]
Fix released as 0.5.2
