### ISSUE TITLE
There are no entries to pick from

### ISSUE THREAD

**Issue by bondz** [KnisterPeter/vscode-jira#29]
This might be related to #18 but I've tried the resolution there and it doesn't work for me.

```json
{
  "jira.baseUrl": "https:\/\/dev-team.atlassian.net\/",
  "jira.projectNames": "DEV"
}
```
VSCode in the output window for Jira shows `Connected to JIRA server at 'https://dev-team.atlassian.net/'`

But when I want to browse or activate issues, I still get the message `No entries to pick from`.

I have also tried using my email and username to authenticate, same result.

**Comment by KnisterPeter** [comment]
@bondz What are you're JIRA project names? Like in #18 its `DEV`?

**Comment by bondz** [comment]
Yes.

**Comment by KnisterPeter** [comment]
What does the following JQL return for you?

    project in (DEV) AND resolution = Unresolved AND assignee in (currentUser()) ORDER BY updated DESC

**Comment by bondz** [comment]
Sorry, `MAX` is the Project Key name. Running that I get, `MAX` is a reserved word.

I fixed it by using the Project name as `jira.projectNames` value. The project name in this case is `MAX Team`

So, my setup became

```json
{
  "jira.baseUrl": "https:\/\/dev-team.atlassian.net\/",
  "jira.projectNames": "\"MAX\""
}
```

Using the project name also works by setting

```json
{
  "jira.baseUrl": "https:\/\/dev-team.atlassian.net\/",
  "jira.projectNames": "\"MAX Dev Team\""
}
```


Same that worked in the jql. Thank you so much 😄

**Comment by KnisterPeter** [comment]
You're welcome :relaxed:
