### ISSUE TITLE
`Browse my issues...` does not remove the extra `/` from the end of the JIRA base URL

### ISSUE THREAD

**Issue by loserock** [KnisterPeter/vscode-jira#30]
The JIRA base URL had been set to `https://jira.example.com/` and everything has been configured. When the user selects `Browse my issue...` in VS Code, then select a ticket like `PROJ-123`, the extension will try opening this link is the browser: `https://jira.example.com//browse/PROJ-123`. So, there could be two slashes (`//`)  int the created URL.

**Comment by loserock** [comment]
Anyway, the extension works like a charm!
Thank you for that!

**Comment by KnisterPeter** [comment]
Thanks
