### ISSUE TITLE
Command 'vscode-jira.setupCredentials' not found, causing extension host to spin 99% cpu

### ISSUE THREAD

**Issue by vasuraman11** [KnisterPeter/vscode-jira#31]
1. Install extension
2. Configure jira-baseUrl and jira-projectNames
3. Command palette, Setup Credentials

Result:
Error command 'vscode.jira.setupCredentials' not found.
A Code Helper instance is running consuming 99% CPU.
Tried uninstall/reinstall, disable/enable, restart VS Code, leaving projectNames blank, no change in behavior.
Confirmed that JIRA API is functional on our server.

**Comment by KnisterPeter** [comment]
Thanks for the report. I'll investigate and try to fix it

**Comment by pdfowler** [comment]
I don't get the CPU issue reported by @vasuraman11, but I do get the message reported. LMK if I can help with diagnostics.

**Comment by orshee** [comment]
Same problem : command 'vscode.jira.setupCredentials' not found

**Comment by leocaseiro** [comment]
In my case, it works if you reload the window after saving your `baseUrl` and `projectName`.
