### ISSUE TITLE
FR: Option to create a new branch from activated jira issue

### ISSUE THREAD

**Issue by dmstern** [KnisterPeter/vscode-jira#32]
It would be nice if vscode would ask me if I would like to have a new branch created for a recently activated jira task.
Something like task management in IntelliJ: https://www.jetbrains.com/help/idea/managing-tasks-and-contexts.html#d953630e223

Suggestion: If you activate a new task with the name `NPROJECT-123 Implement the new feature`, vscode-jira should ask me, if I would like to create a new branch with the name `NPROJECT-123--Implement-the-new-feature`.

**Comment by KnisterPeter** [comment]
Good idea as well. I would like to see both #32 and #15 implemented.
