### ISSUE TITLE
[FR] All the ability to overwrite or extend MyIssues JQL

### ISSUE THREAD

**Issue by jrschumacher** [KnisterPeter/vscode-jira#33]
Currently the [JQL](https://github.com/KnisterPeter/vscode-jira/blob/master/src/commands/list-my-issues.ts#L27-L30) makes some assumptions about the users workflow. If it at all conflicts (and sometimes developers don't have access to the workflows) then it makes the plugin unusable.

1. Specifically, our workflows don't always set resolution so my list is huge. 
2. I'd like to limit these to my current sprint `Sprint in openSprints()`

**Comment by KnisterPeter** [comment]
Good idea. I'll add an option to customize the JQL.
