### ISSUE TITLE
SSO (Single-sign-on providers) not supported for credentials?

### ISSUE THREAD

**Issue by darkvertex** [KnisterPeter/vscode-jira#34]
Hi,

Where I work, our JIRA is configured to be logged in using a Google Apps login tied to the company domain.

I haven't been able to get my credentials working properly with this extension and I suspect maybe SSO logins are not supported? Not to mention that we have 2-factor-auth enabled for our Google Apps login.

Do you think it would be possible to authenticate in an alternative fashion? Maybe some kind of user API key is possible?

**Comment by KnisterPeter** [comment]
@darkvertex To be honest, I have no clue and I don't know about the Atlassian SSO API. Also this does not work well with 2FA. But I guess (not sure) there should be some kind of token access which could could probably get from your JIRA user account.
Any response is greatly appreciated. :smiley:

**Comment by x** [comment]
I was about to do it by creating an auth token here https://id.atlassian.com/manage/api-tokens and then using that auth token as my password.

**Comment by KnisterPeter** [comment]
@x Thanks for reporting. I'll add this to the README as documentation.

**Comment by darkvertex** [comment]
Works perfectly. Thank you for the awesome tip, @x

**Comment by md2perpe** [comment]
The base URL in this case can be taken as `https://<name>.atlassian.net`, where of course `name` should be replaced with whatever you see there in the URL in your browser.
