### ISSUE TITLE
Credentials feedback with showInformationMessage

### ISSUE THREAD

**Issue by leocaseiro** [KnisterPeter/vscode-jira#37]
Hi, thanks for this awesome extension.
I was wondering if it's possible to show an alert/feedback when setting up credentials. I see that's an async process is happening, but if I type the wrong password, it doesn't give me any feedback errors.
The same, if I type it correctly.

@KnisterPeter do you think is hard to add a feedback (`showInformationMessage`) for that?

**Comment by KnisterPeter** [comment]
@leocaseiro : Thats a good point.
