### ISSUE TITLE
Feature suggestions

### ISSUE THREAD

**Issue by toropanov** [KnisterPeter/vscode-jira#38]
Could you please add state labels in browser of issues.
Plus logging task is also can be useful.
And please add filter of only current sprint tasks (sprint in openSprints())

**Comment by KnisterPeter** [comment]
@tanotify First of all thanks for your suggestion. :smiley: 
It would be very helpful if you only suggest one feature per issue, so please split your suggestion into multiple ones.
In addition I would ask you if you could write a bit more in details what you want to suggest. The best for filter update would be to write a proper JQL (JIRA Query Language) statement so I could view and test it. Most helpful, if possible, would be a JIRA demo/example.

**Comment by ssnyder** [comment]
I too would love to filter only current sprint tasks! 
Providing a filter JQL could solve many issues as well (and could be a workaround for the open sprint request)
