### ISSUE TITLE
No JIRA client configured. Setup baseUrl, projectNames, username and password

### ISSUE THREAD

**Issue by ymeunier** [KnisterPeter/vscode-jira#39]
Hi,
It seems to me that I have configured my client correctly, but I still have this error.
I tried with the escape character as shown on another issue, but that's not better. 
How to see the execution trace of the extension to debug it ?

Best regards,
Yann

**Comment by KnisterPeter** [comment]
@ymeunier Thanks for reporting. Did you try to execute 'reload window' after your setup? I guess that could/will help.
There is not real debug log right now.

**Comment by ymeunier** [comment]
Yes @KnisterPeter  ! :)

**Comment by KnisterPeter** [comment]
Your welcome :smiley:

**Comment by ymeunier** [comment]
My problem is not solve :)

**Comment by ymeunier** [comment]
I say yes for reload Windows @KnisterPeter  :)

**Comment by KnisterPeter** [comment]
Ah, got it :smile: Sorry for closing

**Comment by KnisterPeter** [comment]
@ymeunier You can try to open the output panels. There is a `vscode-jira` panel as well. There might be some more information.
