### ISSUE TITLE
Error Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by sbarrat** [KnisterPeter/vscode-jira#5]
I installed, setup jira.baseUrl and jira.projectNames, set Jira Setup Credentials, no message, and when Browser my isses show this error

**Comment by KnisterPeter** [comment]
I will try to inspect this. Can you attach at least a screenshot with the error message?
A line number of the error and a file would be even better.

**Comment by sbarrat** [comment]
I cant locate or debug, if you can guide me... I attach you two screenshots

[cid:388b042a-dfc2-4224-b444-c6bee6479684]
[cid:a80516ac-9451-4f9c-a305-81b8bbb03654]


________________________________
De: Markus Wolf <notifications@github.com>
Enviado: miércoles, 4 de octubre de 2017 19:53:08
Para: KnisterPeter/vscode-jira
Cc: Ruben Lacasa Mas; Author
Asunto: Re: [KnisterPeter/vscode-jira] Error Cannot read property 'map' of undefined (#5)


I will try to inspect this. Can you attach at least a screenshot with the error message?
A line number of the error and a file would be even better.

**Comment by KnisterPeter** [comment]
You have to attach (drag-n-drop) the screen in the issue at github. :wink:

**Comment by sbarrat** [comment]
![captura de pantalla de 2017-10-04 20-36-32](https://user-images.githubusercontent.com/344632/31216635-96ec0b66-a9b4-11e7-93a7-7c4184380375.png)

**Comment by sbarrat** [comment]
![captura de pantalla de 2017-10-04 20-36-57](https://user-images.githubusercontent.com/344632/31216645-9ef1a9ec-a9b4-11e7-8942-0d98236a3f79.png)

**Comment by KnisterPeter** [comment]
Tracked down the source and it may be possible that there are no issues for this JQL query:
```
project in (PRJ1,PRJ2) AND resolution = Unresolved AND assignee in (currentUser()) ORDER BY updated DESC
```
Can you test this? Please replace 'PRJ1,PRJ2' with your project names.

**Comment by sbarrat** [comment]
I test it and i its work, I tried the plugin again in visual studio and its work now. Thank you

________________________________
De: Markus Wolf <notifications@github.com>
Enviado: jueves, 5 de octubre de 2017 10:43:49
Para: KnisterPeter/vscode-jira
Cc: Ruben Lacasa Mas; Author
Asunto: Re: [KnisterPeter/vscode-jira] Error Cannot read property 'map' of undefined (#5)


Tracked down the source and it may be possible that there are no issues for this JQL query:

project in (PRJ1,PRJ2) AND resolution = Unresolved AND assignee in (currentUser()) ORDER BY updated DESC


Can you test this?

**Comment by KnisterPeter** [comment]
Your welcome
